Repository percy/cli, pull requests merged in 2021-09, with the labels that each got.

#479 🔊 Add log to warn when SDK user agent is missing
  packages/cli-build/src/commands/build/finalize.js
  packages/cli-build/src/commands/build/wait.js
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-upload/src/commands/upload.js
  packages/client/src/client.js
  packages/client/test/client.test.js
  packages/core/test/percy.test.js
  packages/core/test/snapshot.test.js
Labels: ✨ enhancement

#549 ♻️ Refactor page, network, and session handling
  packages/core/src/browser.js
  packages/core/src/network.js
  packages/core/src/page.js
  packages/core/src/session.js
  packages/core/test/discovery.test.js
  packages/core/test/snapshot.test.js
Labels: 🐛 bug, ✨ enhancement

#556 🐛 Do not capture scripts or XHR requests when JS is not enabled
  packages/core/src/discovery.js
  packages/core/src/network.js
  packages/core/src/percy.js
  packages/core/test/discovery.test.js
Labels: 🐛 bug

#565 🐛 Fix the eta shown when installing the browser
  packages/core/src/install.js
  packages/core/test/unit/install.test.js
Labels: 🐛 bug
