Repository percy/cli, pull requests merged in 2021-06, with the labels that each got.

#369 ♻️ Refactor core discovery queue
  packages/cli-build/README.md
  packages/cli-build/src/commands/build/finalize.js
  packages/cli-build/src/commands/build/wait.js
  packages/cli-command/src/command.js
  packages/cli-exec/src/commands/exec/index.js
  packages/cli-exec/src/commands/exec/start.js
  packages/cli-exec/test/exec.test.js
  packages/cli-exec/test/stop.test.js
  packages/cli-snapshot/README.md
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/test/snapshot.test.js
  packages/cli-upload/src/commands/upload.js
  packages/client/README.md
  packages/client/package.json
  packages/client/src/client.js
  packages/client/src/request.js
  packages/client/test/client.test.js
  packages/core/README.md
  packages/core/src/browser.js
  packages/core/src/config.js
  packages/core/src/discovery.js
  packages/core/src/discovery/discoverer.js
  packages/core/src/install.js
  packages/core/src/network.js
  packages/core/src/page.js
  packages/core/src/percy.js
  packages/core/src/queue.js
  packages/core/src/server.js
  packages/core/src/utils.js
  packages/core/src/utils/assert.js
  packages/core/src/utils/bytes.js
  packages/core/src/utils/percy-css.js
  packages/core/src/utils/resources.js
  packages/core/src/utils/url.js
  packages/core/src/utils/wait-for.js
  packages/core/test/capture.test.js
  packages/core/test/discovery.test.js
  packages/core/test/percy-css.test.js
  packages/core/test/percy.test.js
  packages/core/test/server.test.js
  packages/core/test/snapshot.test.js
  packages/core/test/unit/install.test.js
  packages/core/test/unit/queue.test.js
  packages/core/types/index.d.ts
  packages/core/types/index.test-d.ts
  packages/sdk-utils/src/post-snapshot.js
  packages/sdk-utils/test/helpers.js
  packages/sdk-utils/test/index.test.js
  packages/sdk-utils/test/server.js
  scripts/test.js
Labels: breaking, enhancement

#370 ✨ Allow setting client's API url via an environment variable
  packages/client/src/client.js
  packages/client/test/proxy.test.js
Labels: enhancement

#372 🐛 Fix unintentionally removing the default queue concurrency
  packages/core/src/percy.js
  packages/core/src/queue.js
Labels: bug

#373 ♻️ Post core refactor tweaks
  packages/core/src/discovery.js
  packages/core/src/network.js
  packages/core/src/page.js
  packages/core/src/percy.js
  packages/core/src/queue.js
  packages/core/test/unit/queue.test.js
Labels: bug, enhancement

#376 ✨ Better progress logging
  packages/cli-build/src/commands/build/wait.js
  packages/cli-build/test/wait.test.js
  packages/client/src/client.js
  packages/core/README.md
  packages/core/package.json
  packages/core/src/install.js
  packages/core/src/percy.js
  packages/core/src/queue.js
  packages/core/test/percy.test.js
  packages/core/test/unit/install.test.js
  packages/logger/src/browser.js
  packages/logger/src/logger.js
  packages/logger/test/helpers.js
  packages/logger/test/logger.test.js
  scripts/chromium-revision
  yarn.lock
Labels: enhancement

#382 ✨ Allow snapshotting a list of pages to utilize the base-url flag
  packages/cli-command/src/command.js
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/test/snapshot.test.js
  packages/config/src/validate.js
  packages/config/test/index.test.js
  packages/core/src/config.js
Labels: enhancement

#383 ✨ Allow setting discovery browser cookies
  packages/core/README.md
  packages/core/src/browser.js
  packages/core/src/config.js
  packages/core/src/page.js
  packages/core/src/percy.js
  packages/core/test/discovery.test.js
Labels: enhancement

#385 🐛 Ignore env git stderr logs
  packages/env/src/utils.js
Labels: bug

#387 🐛 Fix percy-specific css resource url
  packages/core/src/percy.js
  packages/core/src/utils.js
  packages/core/test/snapshot.test.js
Labels: bug

#390 🐛 Always ignore existing root resources during asset discovery
  packages/core/src/discovery.js
  packages/core/test/discovery.test.js
Labels: bug

#393 🐛 Fix additional snapshot options
  packages/core/src/percy.js
  packages/core/test/snapshot.test.js
Labels: bug

#398 🥅 Check version of Node, exit if not supported
  packages/cli/index.js
Labels: enhancement

#400 ✨ Do not wait for remote requests to idle during asset discovery
  packages/core/src/network.js
  packages/core/src/percy.js
  packages/core/test/discovery.test.js
Labels: enhancement
