Repository percy/cli, pull requests merged in 2021-07, with the labels that each got.

#405 🐛 Serialize iframe document URLs
  karma.config.js
  packages/dom/src/serialize-frames.js
  packages/dom/test/serialize-frames.test.js
Labels: bug

#413 🐛 Fix default proxy port
  packages/client/src/request.js
  packages/client/test/proxy.test.js
Labels: bug

#406 ♻️ Refactor percy/config utils
  packages/config/src/defaults.js
  packages/config/src/load.js
  packages/config/src/migrate.js
  packages/config/src/normalize.js
  packages/config/src/utils.js
  packages/config/src/validate.js
  packages/config/test/index.test.js
  packages/core/src/config.js
Labels: enhancement

#408 🙈 Update coverage ignore statements for race conditions
  packages/core/src/browser.js
  packages/core/src/page.js
Labels: maintenance

#416 ✨ Add per-snapshot config validation!
  packages/core/README.md
  packages/core/src/config.js
  packages/core/src/index.js
  packages/core/src/percy.js
  packages/core/test/snapshot.test.js
Labels: enhancement

#417 ✨ Validate snapshot command page listings
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/src/hooks/init.js
  packages/cli-snapshot/test/snapshot.test.js
Labels: enhancement

#418 ✨ Add static snapshot overrides option
  packages/cli-snapshot/README.md
  packages/cli-snapshot/package.json
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/test/snapshot.test.js
  yarn.lock
Labels: enhancement

#419 ✨ Add queue concurrency to the upload command
  packages/cli-upload/src/commands/upload.js
  packages/cli-upload/src/config.js
  packages/cli-upload/test/upload.test.js
Labels: enhancement

#422 ⬆️ Upgrade dependencies
  .github/.cache-key
  package.json
  packages/cli-snapshot/package.json
  packages/cli-upload/package.json
  packages/config/package.json
  packages/core/package.json
  packages/sdk-utils/package.json
  rollup.config.js
  yarn.lock
Labels: dependencies

#431 🐛 Ensure core schemas are loaded before dependent snapshot schemas
  packages/cli-command/test/command.test.js
  packages/cli-exec/src/hooks/init.js
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/src/hooks/init.js
  packages/cli-upload/src/hooks/init.js
  packages/config/src/validate.js
  packages/config/test/index.test.js
  packages/core/src/config.js
  packages/core/src/index.js
Labels: bug

#434 ✨ Add upload option to strip file extensions
  packages/cli-upload/src/commands/upload.js
  packages/cli-upload/src/config.js
  packages/cli-upload/src/resources.js
  packages/cli-upload/test/upload.test.js
Labels: enhancement

#371 ✨ Roll asset discovery browser to Chrome 92
  .github/.cache-key
  packages/core/src/install.js
  scripts/chromium-revision
Labels: enhancement

#448 🙈 Fix coverage ignore statement for racey errors
  packages/core/src/page.js
Labels: maintenance

#447 ✨ Add static snapshot clean-urls and rewrites options
  packages/cli-snapshot/README.md
  packages/cli-snapshot/package.json
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/test/snapshot.test.js
  packages/config/src/normalize.js
  packages/config/test/index.test.js
  yarn.lock
Labels: enhancement

#450 ✨ Normalize config with schemas
  packages/cli-config/src/commands/config/migrate.js
  packages/cli-snapshot/src/config.js
  packages/config/src/load.js
  packages/config/src/migrate.js
  packages/config/src/normalize.js
  packages/config/src/utils.js
  packages/config/src/validate.js
  packages/config/test/index.test.js
  packages/core/src/config.js
  packages/core/src/percy.js
  packages/core/src/server.js
  packages/core/test/percy.test.js
  packages/core/test/server.test.js
  packages/core/test/snapshot.test.js
Labels: ✨ enhancement

#452 🧹 Update release drafter config
  .github/release-drafter.yml
Labels: 🧹 maintenance

#453 🐛 Fix enableJavaScript default for snapshot discovery
  packages/core/src/percy.js
  packages/core/test/discovery.test.js
Labels: 🐛 bug

#454 📝 Update upload and snapshot readmes
  packages/cli-snapshot/README.md
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-upload/README.md
Labels: 📝 documentation

#456 ✨ Allow registering multiple config migrations at a time
  packages/cli-exec/src/hooks/init.js
  packages/config/src/migrate.js
  packages/config/src/normalize.js
  packages/config/test/index.test.js
  packages/core/src/config.js
  packages/core/src/index.js
  packages/core/test/unit/config.test.js
Labels: ✨ enhancement

#457 ⬆️ Update dependencies on and allow github-actions management by dependabot
  .github/dependabot.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/typecheck.yml
  .github/workflows/windows.yml
  packages/core/package.json
  yarn.lock
Labels: ⬆️⬇️ dependencies

#465 ✨ Refactor static snapshot logic into utils
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/utils.js
Labels: ✨ enhancement
