Repository percy/cli, pull requests merged in 2021-08, with the labels that each got.

#469 ✨ Improve network tracking resilience
  packages/core/src/network.js
  packages/core/test/discovery.test.js
Labels: ✨ enhancement

#473 🧹 Fix stale issue label
  .github/workflows/stale.yml
Labels: 🧹 maintenance

#486 ✨ Install the correct Chromium binary for arm Macs
  packages/core/src/install.js
  packages/core/test/unit/install.test.js
  scripts/chromium-revision
Labels: ✨ enhancement

#490 🐛 Fix situations where asset discovery might hang
  packages/core/src/browser.js
  packages/core/src/network.js
  packages/core/src/page.js
  packages/core/src/percy.js
  packages/core/test/discovery.test.js
Labels: 🐛 bug

#491 🐛 Wait for isolated networks to idle
  packages/core/src/network.js
  packages/core/src/page.js
  packages/core/test/discovery.test.js
Labels: 🐛 bug

#492 ✨ Add --debug discovery flag
  packages/cli-command/src/command.js
  packages/cli-command/src/flags.js
  packages/cli-command/test/command.test.js
  packages/cli-exec/README.md
  packages/cli-snapshot/README.md
  packages/core/README.md
  packages/core/src/percy.js
  packages/core/test/percy.test.js
  packages/logger/src/index.js
  packages/logger/test/logger.test.js
Labels: ✨ enhancement

#493 🐛 Fix small config util bugs
  packages/config/src/utils.js
  packages/config/test/index.test.js
Labels: 🐛 bug

#494 ✨ Add deprecate config migrate util
  packages/config/src/migrate.js
  packages/config/src/utils.js
  packages/config/test/index.test.js
  packages/core/src/config.js
  packages/core/test/snapshot.test.js
  packages/core/test/unit/config.test.js
Labels: ✨ enhancement

#495 ♻ Small revision to the deprecate migrate util api
  packages/config/src/migrate.js
  packages/config/test/index.test.js
  packages/core/src/config.js
  packages/core/test/unit/config.test.js
Labels: ✨ enhancement

#496 ✨ Allow automatically deprecating and mapping CLI flags
  packages/cli-command/src/command.js
  packages/cli-command/test/command.test.js
Labels: ✨ enhancement

#497 🐛 Do not replace initial overrides with empty flags
  packages/cli-command/src/command.js
  packages/cli-command/test/command.test.js
Labels: 🐛 bug

#498 💥✨ Add include/exclude cli-snapshot options & deprecate files/ignore
  packages/cli-snapshot/README.md
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/src/utils.js
  packages/cli-snapshot/test/common.test.js
  packages/cli-snapshot/test/directory.test.js
  packages/cli-snapshot/test/file.test.js
  packages/cli-snapshot/test/snapshot.test.js
  packages/cli-snapshot/test/unit/config.test.js
Labels: ✨ enhancement, 💥 breaking

#508 ✨ Allow proxying HTTP requests with client request util
  packages/cli-exec/src/commands/exec/ping.js
  packages/cli-exec/src/commands/exec/stop.js
  packages/client/src/client.js
  packages/client/src/request.js
  packages/client/test/client.test.js
  packages/client/test/proxy.test.js
  packages/client/test/unit/request.test.js
Labels: ✨ enhancement

#512 🐛 Wait for network idle for responsive asset discovery
  packages/core/src/percy.js
  packages/core/test/discovery.test.js
Labels: 🐛 bug

#515 🐛 Fix reference error when static config options are not defined
  packages/cli-snapshot/src/config.js
Labels: 🐛 bug

#514 ✨ Accept additional snapshot execute options for various states
  packages/core/src/config.js
  packages/core/src/page.js
  packages/core/src/percy.js
  packages/core/test/discovery.test.js
  packages/core/test/snapshot.test.js
Labels: ✨ enhancement

#516 ✨ Accept sitemaps with the snapshot command!
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/src/utils.js
  packages/cli-snapshot/test/sitemap.test.js
Labels: ✨ enhancement

#518 📝 Add docs for snapshotting sitemaps
  packages/cli-snapshot/README.md
  packages/cli-snapshot/src/commands/snapshot.js
Labels: 📝 documentation

#517 🐛 Fix sitemap unique URL filtering bug
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/test/sitemap.test.js
Labels: 🐛 bug

#529 🐛 Fix bug when providing execute without before snapshot
  packages/core/src/page.js
  packages/core/test/snapshot.test.js
Labels: 🐛 bug
