Repository percy/cli, pull requests merged in 2021-01, with the labels that each got.

#129 🐛 @percy/env parallel fixes
  packages/env/src/environment.js
  packages/env/test/appveyor.test.js
  packages/env/test/azure.test.js
  packages/env/test/bitbucket.test.js
  packages/env/test/buildkite.test.js
  packages/env/test/circle.test.js
  packages/env/test/codeship.test.js
  packages/env/test/defaults.test.js
  packages/env/test/drone.test.js
  packages/env/test/gitlab.test.js
  packages/env/test/heroku.test.js
  packages/env/test/jenkins.test.js
  packages/env/test/probo.test.js
  packages/env/test/semaphore.test.js
  packages/env/test/travis.test.js
Labels: bug

#130 ✨ Export CLI commands
  packages/cli-build/src/index.js
  packages/cli-config/src/index.js
  packages/cli-exec/src/index.js
  packages/cli-snapshot/src/index.js
  packages/cli-upload/src/index.js
Labels: enhancement

#133 🐛 Use absolute path for image upload root URL
  packages/cli-upload/src/resources.js
  packages/cli-upload/test/upload.test.js
Labels: bug

#138 💥 Rename `--disable-asset-cache` flag to `--disable-cache`
  packages/cli-command/README.md
  packages/cli-command/src/flags.js
  packages/cli-command/test/command.test.js
  packages/cli-command/types/index.d.ts
  packages/cli-command/types/index.test-d.ts
  packages/cli-exec/README.md
  packages/cli-snapshot/README.md
  packages/core/README.md
  packages/core/src/config.js
  packages/core/src/discoverer.js
  packages/core/test/asset-discovery.test.js
  packages/core/types/index.d.ts
  packages/core/types/index.test-d.ts
Labels: breaking, enhancement

#139 🐛 Fix config migration for disable-cache
  packages/cli-config/src/commands/config/migrate.js
  packages/cli-config/test/migrate.test.js
Labels: bug

#128 🔥 Remove dependency on Puppeteer
  .gitignore
  packages/cli-command/test/command.test.js
  packages/cli-snapshot/README.md
  packages/core/README.md
  packages/core/package.json
  packages/core/src/config.js
  packages/core/src/discoverer.js
  packages/core/src/discovery/browser.js
  packages/core/src/discovery/discoverer.js
  packages/core/src/discovery/network.js
  packages/core/src/discovery/page.js
  packages/core/src/index.js
  packages/core/src/percy.js
  packages/core/src/queue.js
  packages/core/src/utils/assert.js
  packages/core/src/utils/capture.js
  packages/core/src/utils/idle.js
  packages/core/src/utils/install-browser.js
  packages/core/src/utils/percy-css.js
  packages/core/src/utils/wait-for.js
  packages/core/test/asset-discovery.test.js
  packages/core/test/capture.test.js
  packages/core/test/helpers/index.js
  packages/core/test/install-browser.test.js
  packages/core/test/percy.test.js
  packages/core/types/index.d.ts
  packages/core/types/index.test-d.ts
  yarn.lock
Labels: breaking, enhancement

#140 ✨ Even better logging
  packages/cli-build/src/commands/build/finalize.js
  packages/cli-build/src/commands/build/wait.js
  packages/cli-build/test/finalize.test.js
  packages/cli-build/test/wait.test.js
  packages/cli-command/src/command.js
  packages/cli-command/test/command.test.js
  packages/cli-config/src/commands/config/create.js
  packages/cli-config/src/commands/config/migrate.js
  packages/cli-config/src/commands/config/validate.js
  packages/cli-config/test/create.test.js
  packages/cli-config/test/helpers.js
  packages/cli-config/test/migrate.test.js
  packages/cli-config/test/validate.test.js
  packages/cli-exec/src/commands/exec/index.js
  packages/cli-exec/src/commands/exec/ping.js
  packages/cli-exec/src/commands/exec/start.js
  packages/cli-exec/src/commands/exec/stop.js
  packages/cli-exec/test/exec.test.js
  packages/cli-exec/test/helpers.js
  packages/cli-exec/test/ping.test.js
  packages/cli-exec/test/start.test.js
  packages/cli-exec/test/stop.test.js
  packages/cli-snapshot/src/commands/snapshot.js
  packages/cli-snapshot/test/snapshot.test.js
  packages/cli-upload/src/commands/upload.js
  packages/cli-upload/test/upload.test.js
  packages/config/src/load.js
  packages/config/test/index.test.js
  packages/core/package.json
  packages/core/src/discovery/browser.js
  packages/core/src/discovery/discoverer.js
  packages/core/src/discovery/network.js
  packages/core/src/discovery/page.js
  packages/core/src/percy.js
  packages/core/src/server.js
  packages/core/src/utils/capture.js
  packages/core/src/utils/install-browser.js
  packages/core/src/utils/percy-css.js
  packages/core/src/utils/wait-for.js
  packages/core/test/asset-discovery.test.js
  packages/core/test/capture.test.js
  packages/core/test/helpers/index.js
  packages/core/test/percy.test.js
  packages/core/test/server.test.js
  packages/logger/README.md
  packages/logger/index.js
  packages/logger/package.json
  packages/logger/src/colors.js
  packages/logger/src/index.js
  packages/logger/src/logger.js
  packages/logger/test/.babelrc
  packages/logger/test/helper.js
  packages/logger/test/index.test.js
  packages/sdk-utils/index.js
  packages/sdk-utils/package.json
  packages/sdk-utils/test/helper.js
  packages/sdk-utils/test/index.test.js
  yarn.lock
Labels: breaking, enhancement

#145 ✨ Lazily create sdk-util logger for testing purposes
  packages/sdk-utils/index.js
Labels: enhancement

#149 ✅ Fix @percy/dom Karma and Webpack issues
  packages/dom/karma.conf.js
  packages/dom/package.json
  packages/dom/rollup.config.js
  packages/dom/test/helpers.js
  packages/dom/test/index.js
  packages/dom/test/serialize-canvas.test.js
  packages/dom/test/serialize-css.test.js
  packages/dom/test/serialize-dom.test.js
  packages/dom/test/serialize-frames.test.js
  packages/dom/test/serialize-inputs.test.js
  yarn.lock
Labels: Maintenance

#150 ♻ Adjust how the browser download script determines executable path
  packages/core/src/utils/install-browser.js
Labels: maintenance
