Repository percy/cli, pull requests merged in 2022-04, with the labels that each got.

#853 🐛 Fix supressed validation error causing options to not be scrubbed
  packages/core/src/config.js
  packages/core/test/snapshot.test.js
Labels: 🐛 bug

#858 🐛 Remove relative path from package files
  packages/cli-build/package.json
  packages/cli-command/package.json
  packages/cli-config/package.json
  packages/cli-exec/package.json
  packages/cli-snapshot/package.json
  packages/cli-upload/package.json
  packages/cli/package.json
  packages/client/package.json
  packages/config/package.json
  packages/core/package.json
  packages/env/package.json
  packages/logger/package.json
  packages/sdk-utils/package.json
Labels: 🐛 bug

#862 ✅ Include all core test helpers in packaged files
  packages/config/test/helpers.js
  packages/core/package.json
Labels: 🐛 bug

#863 🐛 Audit package file exports
  packages/cli-command/package.json
  packages/config/package.json
  packages/env/package.json
Labels: 🐛 bug

#865 ✅ More test adjustments
  .gitignore
  package.json
  packages/cli/test/commands.test.js
  packages/cli/test/helpers.js
  packages/cli/test/update.test.js
  packages/config/package.json
  packages/config/test/helpers.js
  packages/config/test/index.test.js
  packages/core/package.json
  packages/core/test/helpers/index.js
  packages/core/test/helpers/server.js
  packages/core/test/unit/install.test.js
  packages/core/test/unit/server.test.js
  packages/logger/test/helpers.js
  packages/sdk-utils/test/server.js
Labels: 🐛 bug

#866 🐛 Core snapshot validation bug fixes
  packages/config/src/validate.js
  packages/core/src/snapshot.js
  packages/core/test/snapshot-multiple.test.js
Labels: 🐛 bug

#868 🐛 Fix readme generation script
  packages/cli-command/bin/readme.js
  packages/cli-command/package.json
Labels: 🐛 bug

#877 ✨@percy/config util improvements
  packages/config/src/utils/merge.js
  packages/config/src/utils/normalize.js
  packages/config/test/index.test.js
Labels: ✨ enhancement

#879 🔨 Repo script fixups
  package.json
  scripts/build.js
  yarn.lock
Labels: 🧹 maintenance

#883 🐛 Check for alternate casing when determining dom snapshot syntax
  packages/core/src/snapshot.js
  packages/core/test/snapshot.test.js
Labels: 🐛 bug

#885 🐛 Make config normalize skip option behave as expected
  packages/config/src/utils/normalize.js
Labels: 🐛 bug

#895 🐛 Fix Chrome Revision script
  package.json
  scripts/chromium-revision.js
Labels: 🐛 bug
