Repository percy/cli, pull requests merged in 2022-09, with the labels that each got.

#1051 🐛 Serialize all CSSOM rules
  packages/dom/src/serialize-cssom.js
  packages/dom/test/serialize-css.test.js
Labels: 🐛 bug

#1055 🐛 Use a file URL when importing snapshot files
  packages/cli-snapshot/src/snapshot.js
Labels: 🐛 bug

#1056 🐛 Restrict CSSOM serialization to modified stylesheets
  packages/dom/src/serialize-cssom.js
  packages/dom/test/helpers.js
  packages/dom/test/serialize-css.test.js
Labels: 🐛 bug

#1057 🐛 Fix sdk-utils websocket constructor hanging
  packages/sdk-utils/src/logger.js
Labels: 🐛 bug

#1069 🐛 Remove remote logger
  packages/core/src/api.js
  packages/core/src/server.js
  packages/core/test/api.test.js
  packages/core/test/unit/server.test.js
  packages/sdk-utils/README.md
  packages/sdk-utils/src/logger.js
  packages/sdk-utils/src/percy-enabled.js
  packages/sdk-utils/test/helpers.js
  packages/sdk-utils/test/index.test.js
Labels: 🐛 bug

#1075 🗑 Remove deprecated pre-release options
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/src/snapshot.js
  packages/cli-snapshot/test/unit/config.test.js
  packages/core/src/config.js
  packages/core/test/snapshot.test.js
  packages/core/test/unit/config.test.js
Labels: 🧹 maintenance

#1076 ♻️ Move devicePixelRatio snapshot discovery option
  packages/core/src/config.js
  packages/core/src/snapshot.js
  packages/core/test/discovery.test.js
  packages/core/test/snapshot.test.js
  packages/core/test/unit/config.test.js
Labels: 🐛 bug

#1078 🐛 Add sdk-utils logger mocking test helpers
  packages/sdk-utils/src/logger.js
  packages/sdk-utils/test/helpers.js
  packages/sdk-utils/test/index.test.js
Labels: 🐛 bug

#1077 ♻️ Refactor core queues
  packages/cli-upload/src/upload.js
  packages/cli-upload/src/utils.js
  packages/cli-upload/test/upload.test.js
  packages/core/src/api.js
  packages/core/src/discovery.js
  packages/core/src/network.js
  packages/core/src/page.js
  packages/core/src/percy.js
  packages/core/src/queue.js
  packages/core/src/snapshot.js
  packages/core/test/discovery.test.js
  packages/core/test/percy.test.js
  packages/core/test/snapshot-multiple.test.js
  packages/core/test/snapshot.test.js
  packages/core/test/unit/queue.test.js
Labels: ✨ enhancement

#1086 ♻️ Adjust how direct snapshot uploads are handled
  packages/cli-upload/src/upload.js
  packages/cli-upload/src/utils.js
  packages/core/src/discovery.js
  packages/core/src/percy.js
  packages/core/src/snapshot.js
  packages/core/test/percy.test.js
Labels: 🧹 maintenance
