Repository percy/cli, pull requests merged in 2022-08, with the labels that each got.

#1020 ✨ Config schema and validation improvements
  packages/config/src/validate.js
  packages/config/test/index.test.js
Labels: ✨ enhancement

#1028 🐛 Update snapshot typedefs
  packages/core/types/index.d.ts
  packages/core/types/index.test-d.ts
Labels: 🐛 bug

#1031 ✨ Improve testing mode and support in sdk-utils based tests
  packages/core/src/api.js
  packages/core/test/api.test.js
  packages/sdk-utils/package.json
  packages/sdk-utils/src/logger.js
  packages/sdk-utils/src/request.js
  packages/sdk-utils/test/helpers.js
  packages/sdk-utils/test/index.test.js
  packages/sdk-utils/test/server.js
Labels: ✨ enhancement

#1034 🐛 Do not implicitly reset testing mode remote connections
  packages/core/src/api.js
Labels: 🐛 bug

#1038 ✨Add core option to skip asset discovery
  packages/cli-command/README.md
  packages/cli-command/src/command.js
  packages/cli-command/test/flags.test.js
  packages/cli-upload/src/upload.js
  packages/core/src/percy.js
  packages/core/src/snapshot.js
  packages/core/test/discovery.test.js
Labels: ✨ enhancement

#1039 ✨ Format logger messages padded by newlines
  packages/cli/src/update.js
  packages/cli/test/update.test.js
  packages/logger/src/logger.js
  packages/logger/test/logger.test.js
Labels: ✨ enhancement

#1042 🐛 Fix static server base-url issue
  packages/core/src/api.js
  packages/core/src/snapshot.js
  packages/core/test/snapshot-multiple.test.js
Labels: 🐛 bug

#1040 ✨ Add CLI command framework features
  packages/cli-command/package.json
  packages/cli-command/src/command.js
  packages/cli-command/src/flags.js
  packages/cli-command/src/help.js
  packages/cli-command/src/parse.js
  packages/cli-command/test/flags.test.js
  packages/cli-command/test/help.test.js
  packages/cli-command/test/parse.test.js
  packages/cli-exec/src/common.js
  packages/cli-exec/src/exec.js
  packages/cli-exec/src/ping.js
  packages/cli-exec/src/start.js
  packages/cli-exec/src/stop.js
Labels: ✨ enhancement

#1044 📝 Update cli-build readme with build:id command
  packages/cli-build/README.md
Labels: 📝 documentation
