Repository percy/cli, pull requests merged in 2022-03, with the labels that each got.

#807 ✅ Update install unit tests to use mock filesystem
  packages/core/test/unit/install.test.js
Labels: 🧹 maintenance

#808 ✨ Use default widths instead of throwing an error when missing
  packages/core/src/snapshot.js
  packages/core/test/snapshot.test.js
Labels: ✨ enhancement

#806 ♻️ Move browser timeout default to other launch option defaults
  packages/core/src/browser.js
Labels: 🧹 maintenance

#805 ♻️ Improve build failure handling
  packages/core/src/api.js
  packages/core/src/percy.js
  packages/core/src/queue.js
  packages/core/test/api.test.js
  packages/core/test/percy.test.js
  packages/core/test/snapshot.test.js
  packages/sdk-utils/src/post-snapshot.js
  packages/sdk-utils/test/helpers.js
  packages/sdk-utils/test/index.test.js
  packages/sdk-utils/test/server.js
Labels: ✨ enhancement

#809 ✨ Accept alternate core snapshot syntaxes
  .eslintrc
  packages/cli-snapshot/src/config.js
  packages/cli-snapshot/src/snapshot.js
  packages/core/README.md
  packages/core/package.json
  packages/core/src/api.js
  packages/core/src/config.js
  packages/core/src/percy.js
  packages/core/src/snapshot.js
  packages/core/test/discovery.test.js
  packages/core/test/percy.test.js
  packages/core/test/snapshot-multiple.test.js
  packages/core/test/snapshot.test.js
  yarn.lock
Labels: ✨ enhancement

#818 🐛 Fix core snapshot method compatibility with cli-snapshot command
  packages/core/src/api.js
  packages/core/src/percy.js
  packages/core/src/snapshot.js
  packages/core/test/percy.test.js
  packages/core/test/snapshot-multiple.test.js
Labels: 🐛 bug

#831 ✨ Add sdk-utils waitForPercyIdle helper
  packages/sdk-utils/src/index.js
  packages/sdk-utils/src/percy-idle.js
  packages/sdk-utils/test/index.test.js
  packages/sdk-utils/test/server.js
Labels: ✨ enhancement

#832 ✨ Throw an error when a static server directory does not exist
  packages/core/src/server.js
  packages/core/test/snapshot-multiple.test.js
Labels: ✨ enhancement

#833 ✨ Allow alternate snapshot syntaxes to be cancelable
  packages/cli-exec/src/exec.js
  packages/cli-exec/src/start.js
  packages/cli-snapshot/src/snapshot.js
  packages/cli-upload/src/upload.js
  packages/core/src/percy.js
  packages/core/src/snapshot.js
  packages/core/test/percy.test.js
  packages/core/test/snapshot-multiple.test.js
  packages/core/test/snapshot.test.js
Labels: ✨ enhancement

#834 ✨ Allow a function to gather snapshots using alternate syntaxes
  packages/core/src/snapshot.js
  packages/core/test/snapshot-multiple.test.js
Labels: ✨ enhancement

#843 🐛 Insert serialized CSSOM `style` tag after CSSOM `ownerNode`
  packages/dom/src/prepare-dom.js
  packages/dom/src/serialize-cssom.js
  packages/dom/test/serialize-css.test.js
  yarn.lock
Labels: 🐛 bug

#849 🐛 Fix duplicate resource URL issues with `snapshot` method
  packages/core/src/snapshot.js
  packages/core/test/snapshot.test.js
Labels: 🐛 bug

#850 ✨ Automatically include package information with CLI commands
  packages/cli-command/src/command.js
  packages/cli-command/src/parse.js
  packages/cli-command/test/command.test.js
  packages/cli/src/commands.js
  packages/cli/test/commands.test.js
Labels: ✨ enhancement

#848 🐛 Wrap `serializeVideos` in try/catch to catch security errors
  packages/dom/src/serialize-video.js
  packages/dom/test/serialize-videos.test.js
Labels: 🐛 bug
