Repository percy/cli, pull requests merged in 2023-11, with the labels that each got.

#1427 Fixing percyScreenshotEnd response
  packages/webdriver-utils/src/providers/automateProvider.js
  packages/webdriver-utils/test/providers/automateProvider.test.js
Labels: 🐛 bug

#1411 ✨ Implement Warning + Disable Percy for unsupported combinations
  packages/webdriver-utils/src/providers/automateProvider.js
  packages/webdriver-utils/test/providers/automateProvider.test.js
Labels: ✨ enhancement, 🍞 stale

#1408 Fixing FindRegion + Refactor
  packages/webdriver-utils/src/driver.js
  packages/webdriver-utils/src/providers/genericProvider.js
  packages/webdriver-utils/test/driver.test.js
  packages/webdriver-utils/test/providers/genericProvider.test.js
Labels: 🐛 bug

#1440 Resolving race condition in snapshots flush
  packages/core/src/discovery.js
  packages/core/src/queue.js
  packages/core/src/snapshot.js
  packages/core/test/unit/queue.test.js
Labels: 🐛 bug

#1441 ♻️ Refactor: added defaultmap + locking mechanism for intercepts queue
  packages/core/src/config.js
  packages/core/src/discovery.js
  packages/core/src/network.js
  packages/core/src/snapshot.js
  packages/core/src/utils.js
  packages/core/test/discovery.test.js
  packages/core/test/unit/utils.test.js
  packages/core/types/index.d.ts
Labels: 🧹 maintenance
