Repository percy/cli, pull requests merged in 2023-04, with the labels that each got.

#1229 ignored element support implementation
  packages/client/src/client.js
  packages/client/test/client.test.js
  packages/core/src/config.js
Labels: ✨ enhancement

#1230 🐛 cloneNode ensure shallow clone
  packages/dom/src/clone-dom.js
  packages/dom/test/serialize-dom.test.js
Labels: 🐛 bug

#1217 Windows flakes fix attempt 1
  .github/workflows/windows.yml
  scripts/test-helpers.js
Labels: 🧹 maintenance

#1235 Regression status check
  .github/workflows/sdk-regression.yml
Labels: 🧹 maintenance

#1236 SDK Regression fix context conflict
  .github/workflows/sdk-regression.yml
Labels: 🧹 maintenance

#1237 Regression Fix job url and status update
  .github/workflows/sdk-regression.yml
Labels: 🧹 maintenance
