Repository percy/cli, pull requests merged in 2023-06, with the labels that each got.

#1266 🧹 Add debug logs for env package
  packages/client/test/client.test.js
  packages/env/package.json
  packages/env/src/environment.js
Labels: 🧹 maintenance

#1265 ✨ Support loading lazy attribute
  packages/dom/src/clone-dom.js
  packages/dom/src/transform-dom.js
  packages/dom/test/serialize-dom.test.js
  packages/dom/test/transform-dom.test.js
Labels: ✨ enhancement

#1275 ✨ Introduce new config option for cli-snapshot for enabling JS in asset discovery page
  packages/config/test/index.test.js
  packages/core/src/config.js
  packages/core/src/discovery.js
  packages/core/test/discovery.test.js
  packages/core/test/percy.test.js
Labels: ✨ enhancement

#1278 rewrite localhost domain for serialized assets to render.percy.local
  packages/dom/src/utils.js
  packages/dom/test/utils.test.js
Labels: 🐛 bug
