Repository percy/cli, pull requests merged in 2023-02, with the labels that each got.

#1175 🐛 fix device pixel ratio config for percy exec
  packages/core/src/discovery.js
  packages/core/src/snapshot.js
  packages/core/test/discovery.test.js
Labels: 🐛 bug

#1177 :broom: don't show prerelease versions for update in CLI
  packages/cli/src/update.js
  packages/cli/test/update.test.js
Labels: 🧹 maintenance

#1185 ✨ DOM events triggered on clone fixed
  packages/cli/README.md
  packages/core/README.md
  packages/dom/src/clone-dom.js
  packages/dom/src/inject-polyfill.js
  packages/dom/src/serialize-cssom.js
  packages/dom/src/serialize-frames.js
  packages/dom/test/serialize-css.test.js
  packages/dom/test/serialize-dom.test.js
Labels: ✨ enhancement

#1187 👷 update request method for verify tiles, remove warnings banner for app:exec
  packages/cli-app/src/app.js
  packages/cli-command/test/help.test.js
  packages/client/src/client.js
  packages/client/test/client.test.js
Labels: 🧹 maintenance
