Repository percy/cli, pull requests merged in 2023-03, with the labels that each got.

#1193 👷 update error code for retry logic
  packages/client/src/client.js
  packages/client/test/client.test.js
Labels: 🧹 maintenance

#1195 📝 Remove publish info
  packages/cli/README.md
Labels: 📝 documentation

#1196 👷 update retry logic to check response code
  packages/client/src/client.js
Labels: 🧹 maintenance

#1197 🐛 copy full style node for deriving CSS rules
  packages/dom/src/serialize-cssom.js
  packages/dom/src/utils.js
  packages/dom/test/utils.test.js
Labels: 🐛 bug

#1205 ✨ Check review-state in build:wait
  packages/cli-build/src/wait.js
  packages/cli-build/test/wait.test.js
Labels: ✨ enhancement

#1219 Regression use PR branch
  .github/workflows/sdk-regression.yml
Labels: 🧹 maintenance

#1220 Regression: WDIO test v2 and add more SDKs
  .github/workflows/sdk-regression.yml
Labels: 🧹 maintenance
