Repository percy/cli, pull requests merged in 2023-10, with the labels that each got.

#1372 Updated readme for chromium revision update
  packages/core/README.md
  scripts/chromium-revision.js
Labels: 🍞 stale

#1388 ✨ Added token support in percy config
  packages/client/src/client.js
  packages/client/test/client.test.js
  packages/core/src/config.js
  packages/core/src/percy.js
  packages/core/test/percy.test.js
Labels: ✨ enhancement

#1400 [PER-2582] Do not execute git commands when `PERCY_SKIP_GIT_CHECK` is set to True
  packages/env/src/utils.js
  packages/env/test/defaults.test.js
Labels: ✨ enhancement

#1404 [PER-2574] Icons not loading when `noscript` tags are present.
  packages/dom/src/clone-dom.js
  packages/dom/test/serialize-dom.test.js
Labels: 🐛 bug

#1401 ✨ adding endpoint for sending failed event
  packages/cli-exec/src/exec.js
  packages/cli-exec/test/exec.test.js
  packages/client/src/client.js
  packages/client/test/client.test.js
  packages/core/src/api.js
  packages/core/src/utils.js
  packages/core/test/api.test.js
  packages/sdk-utils/src/index.js
  packages/sdk-utils/src/post-build-event.js
  packages/sdk-utils/test/index.test.js
Labels: ✨ enhancement

#1378 :sparkles: Introduce new config option enableLayout for enabling layout testing.
  packages/cli-upload/test/upload.test.js
  packages/client/src/client.js
  packages/client/test/client.test.js
  packages/config/test/index.test.js
  packages/core/src/config.js
  packages/core/src/discovery.js
  packages/core/test/discovery.test.js
  packages/core/types/index.d.ts
Labels: ✨ enhancement

#1415 ✨ Fix percyCSS not getting applied when elements outside `</body>`
  packages/core/src/config.js
  packages/core/src/discovery.js
  packages/core/src/page.js
  packages/core/test/percy.test.js
  packages/core/test/snapshot.test.js
  packages/core/types/index.d.ts
  packages/dom/README.md
  packages/dom/src/serialize-dom.js
  packages/dom/test/helpers.js
  packages/dom/test/serialize-dom.test.js
Labels: ✨ enhancement
