Repository percy/cli, pull requests merged in 2023-09, with the labels that each got.

#1361 :bug: Move out timing.js from sdk-utils
  packages/sdk-utils/src/index.js
  packages/webdriver-utils/src/providers/automateProvider.js
  packages/webdriver-utils/src/util/cache.js
  packages/webdriver-utils/src/util/timing.js
  packages/webdriver-utils/src/util/validations.js
  packages/webdriver-utils/test/util/timing.test.js
Labels: 🐛 bug

#1362 🏗️ Upload executables as assets
  .github/workflows/executable.yml
Labels: 🧹 maintenance

#1364 Move zip logic to executable script
  .github/workflows/executable.yml
  scripts/executable.sh
Labels: 🧹 maintenance

#1370 Percy on Automate: Check if deviceName was passed
  packages/webdriver-utils/src/metadata/metaDataResolver.js
  packages/webdriver-utils/test/metadata/metaDataResolver.test.js
Labels: 🐛 bug

#1377 Removing PercyCSS from CLI for performance benefit
  packages/webdriver-utils/src/providers/genericProvider.js
  packages/webdriver-utils/test/providers/genericProvider.test.js
Labels: ✨ enhancement

#1382 Change freezeAnimation -> freezeAnimatedImage
  packages/core/src/config.js
  packages/core/src/utils.js
  packages/core/test/api.test.js
  packages/webdriver-utils/src/providers/genericProvider.js
Labels: ✨ enhancement
