Repository percy/cli, pull requests merged in 2024-06, with the labels that each got.

#1601 [Snyk] Security upgrade micromatch from 4.0.5 to 4.0.6
  packages/core/package.json
Labels: ⬆️⬇️ dependencies, 🍞 stale

#1625 tags support
  packages/cli-command/src/flags.js
  packages/cli-command/test/command.test.js
  packages/cli-command/test/flags.test.js
  packages/cli-command/test/help.test.js
  packages/cli-upload/test/upload.test.js
  packages/client/src/client.js
  packages/client/src/utils.js
  packages/client/test/client.test.js
  packages/client/test/tagsList.test.js
  packages/core/src/config.js
  packages/core/src/percy.js
  packages/core/src/snapshot.js
Labels: ✨ enhancement

#1628 ✨ Added log collection to logger of sdk utils
  packages/sdk-utils/src/logger.js
  packages/sdk-utils/test/index.test.js
  packages/webdriver-utils/src/providers/playwrightProvider.js
Labels: ✨ enhancement

#1637 tags: minor fixes
  packages/core/src/percy.js
  packages/core/test/percy.test.js
Labels: 🐛 bug
